version: '3.8'

services:
  postgres_db:
    container_name: postgres_db
    image: postgres:15
    restart: always
    # add port mapping to allow db access from localhost
    #  eg jdbc:postgresql://localhost:6000/users
    ports:
      - "6000:${DB_PORT}"
    expose:
      - "${DB_PORT}"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

  api:
    build:
      dockerfile: Dockerfile
      context: "./../api"
    image: api:latest
    depends_on:
      - postgres_db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres_db
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}?schemaName=${DB_SCHEMA}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}

  react-web:
    build:
      dockerfile: Dockerfile
      context: "./../web"
    image: web:latest
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
      - ./../web:/react-web
      - /react-web/node_modules
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}

volumes:
  pgdata:
