name: Web CI


on:
  pull_request:
    branches:
      - main
    paths:
      - "web/**"
#  push:
#    branches:
#      - github-actions-testing
#    paths:
#      - "web/**"

defaults:
  run:
    shell: bash
    working-directory: ./web

jobs:
  docker-build-check:
    runs-on: ubuntu-20.04
    name: Build dockerfile to ensure it works

    steps:
      - uses: actions/checkout@v3
      - name: docker build to check strictness
        id: docker-build
        run: |
          docker build .
  npm-build-check:
    runs-on: ubuntu-latest

#    strategy:
#      matrix:
#        node-version: [12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v3
#      - name: Use Node.js ${{ matrix.node-version }}
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
#          node-version: ${{ matrix.node-version }}
          node-version: 16.x
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
